# Created by GPT-5.6 Sol Max [codex]. Revised by AndyBRoswell.

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$workspace = if ([string]::IsNullOrWhiteSpace($env:GITHUB_WORKSPACE)) { (Get-Location).Path } else { $env:GITHUB_WORKSPACE }
$workspace_full_path = [IO.Path]::GetFullPath($workspace)
$output_directory = [IO.Path]::GetFullPath((Join-Path $workspace_full_path '.vercel/output'))
$directory_separator = [IO.Path]::DirectorySeparatorChar
if ($output_directory.StartsWith("$workspace_full_path$directory_separator", [StringComparison]::Ordinal) -eq $false) {
  throw "Refused to replace a Vercel output directory outside $workspace_full_path."
}

Remove-Item -LiteralPath $output_directory -Recurse -Force -ErrorAction SilentlyContinue
$static_output = Join-Path $output_directory 'static'
New-Item -ItemType Directory -Force $static_output | Out-Null

# Reuse the exact Astro artifact already built and tested. GitHub-hosted Ubuntu runners keep both paths on one filesystem, so hard links avoid copying files.
& /usr/bin/cp -al apps/main/dist/. "$static_output/"
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

# Equivalent routing configuration generated by Vercel CLI 59.5.0 with @vercel/static-build for this Astro project.
$configuration = [ordered]@{
  version = 3
  routes = @(
    foreach ($path in 'assets', '_astro') {
      [ordered]@{
        src = ('^/{0}/(.*)$' -f $path)
        headers = [ordered]@{ 'cache-control' = 'public, max-age=31536000, immutable' }
        continue = $true
      }
    }
    [ordered]@{ handle = 'error' }
    [ordered]@{
      status = 404
      src = '^(?!/api).*$'
      dest = '/404.html'
    }
  )
  crons = @()
}
$configuration | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath (Join-Path $output_directory 'config.json')
