import { defineConfig } from "astro/config";
import preact from "@astrojs/preact";
import starlight from "@astrojs/starlight";
import { Preface } from "./src/components/sidebar/前言.ts";
import { Tools_and_Ideas_to_Improve_Efficiency } from "./src/components/sidebar/提升效率的工具与思想.ts";
import { Courses_Textbooks_and_References } from "./src/components/sidebar/课程、教科书与参考资料.ts";
import { Things_Needed_to_Be_Started_or_Done_as_Soon_as_Possible } from "./src/components/sidebar/需要尽早开始或完成的事项.ts";
import { Future_Trends } from "./src/components/sidebar/未来趋势.ts";
import { FAQ } from "./src/components/sidebar/常见问题.ts";
import { Recommended_Reading_Materials } from "./src/components/sidebar/推荐读物.ts";
import { Epilog } from "./src/components/sidebar/后记.ts";

// https://astro.build/config
export default defineConfig({
  integrations: [
    preact(),
    starlight({
      title: {
        'zh-CN': 'CS 自救指南',
        en: 'CS First Aid',
      },
      tableOfContents: {
        minHeadingLevel: 1,
        maxHeadingLevel: 6,
      },
      components: {
        PageTitle: './src/components/PageTitle.astro',
        Header: './src/components/docs_header.astro',
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/AndyBRoswell/cs-first-aid' },
      ],
      customCss: [
        './src/styles/docs.css',
      ],
      locales: {
        root: {
          label: '简体中文',
          lang: 'zh-CN',
        },
        en: {
          label: 'English',
          lang: 'en',
        }
      },
      // By default, pages are sorted in alphabetical order according to the file `id` when using `autogenerate`. But I use custom orders here instead of keeping `id` attrs ordered.
      // See https://starlight.astro.build/guides/sidebar/#autogenerated-groups
      sidebar: [
        Preface,
        Tools_and_Ideas_to_Improve_Efficiency,
        Courses_Textbooks_and_References,
        Things_Needed_to_Be_Started_or_Done_as_Soon_as_Possible,
        Future_Trends,
        FAQ,
        Recommended_Reading_Materials,
        Epilog,
      ],
    })
  ],
  experimental: {
    rustCompiler: true,
  },
});