import { defineConfig } from "astro/config";
import preact from "@astrojs/preact";
import starlight from "@astrojs/starlight";
import * as sidebar_content from './src/components/sidebar/content.ts'

// https://astro.build/config
export default defineConfig({
  integrations: [
    preact(),
    starlight({
      title: {
        'zh-CN': 'CS 自救指南',
        en: 'CS First Aid',
      },
      tableOfContents: {
        minHeadingLevel: 1,
        maxHeadingLevel: 6,
      },
      components: {
        PageTitle: './src/components/PageTitle.astro',
        Header: './src/components/docs_header.astro',
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/AndyBRoswell/cs-first-aid' },
      ],
      customCss: [
        './src/styles/docs.css',
      ],
      locales: {
        root: {
          label: '简体中文',
          lang: 'zh-CN',
        },
        en: {
          label: 'English',
          lang: 'en',
        }
      },
      // By default, pages are sorted in alphabetical order according to the file `id` when using `autogenerate`. But I use custom orders here instead of keeping `id` attrs ordered.
      // See https://starlight.astro.build/guides/sidebar/#autogenerated-groups
      sidebar: [
        sidebar_content.chapter['前言'],
        sidebar_content.chapter['提升效率的工具与思想'],
        sidebar_content.chapter['课程、教科书与参考资料'],
        sidebar_content.chapter['需要尽早开始或完成的事项'],
        sidebar_content.chapter['未来趋势'],
        sidebar_content.chapter['常见问题'],
        sidebar_content.chapter['推荐读物'],
        sidebar_content.chapter['后记'],
      ],
    })
  ],
  experimental: {
    rustCompiler: true,
  },
});