allowBuilds:
  citation-js: true
  esbuild: true
  sharp: true # Required by Wrangler
  workerd: true # Required by Wrangler
minimumReleaseAgeExclude:
  - astro@7.2.0
packages:
  - "apps/*"
  - "packages/*"
