// Created by GPT-5.6 Terra Max [codex]. Revised by AndyBRoswell.

import type { StarlightUserConfig } from '@astrojs/starlight/types'
import { Preface } from '@/components/sidebar/前言.ts'
import { Tools_and_Ideas } from '@/components/sidebar/工具与思想.ts'
import { Courses_Textbooks_and_References } from '@/components/sidebar/课程、教科书与参考资料.ts'
import { Critical_Goals_and_Time_Windows } from '@/components/sidebar/关键目标与时间窗口.ts'
import { Future_Trends } from '@/components/sidebar/未来趋势.ts'
import { FAQ } from '@/components/sidebar/常见问题.ts'
import { Recommended_Reading_Materials } from '@/components/sidebar/推荐读物.ts'
import { Epilog } from '@/components/sidebar/后记.ts'

export const locales = {
  root: {
    label: '简体中文',
    lang: 'zh-CN',
  },
  en: {
    label: 'English',
    lang: 'en',
  },
} satisfies NonNullable<StarlightUserConfig['locales']>

// By default, pages are sorted in alphabetical order according to the file `id` when using `autogenerate`. But I use custom orders here instead of keeping `id` attrs ordered.
// See https://starlight.astro.build/guides/sidebar/#autogenerated-groups
export const sidebar = [
  Preface,
  Tools_and_Ideas,
  Courses_Textbooks_and_References,
  Critical_Goals_and_Time_Windows,
  Future_Trends,
  FAQ,
  Recommended_Reading_Materials,
  Epilog,
] satisfies NonNullable<StarlightUserConfig['sidebar']>
