// const course_materials = import.meta.glob('./src/data/materials/*.ts', { eager: true });
// console.log(course_materials)

import '@/data/materials/R. A. Adams & C. Essex, Calculus.ts'
import '@/data/materials/龚昇 简明微积分.ts'
import '@/data/materials/同济高数.ts'
import '@/data/materials/T. M. Apostol, Calculus.ts'
import '@/data/materials/Thomas Calculus.ts'
import '@/data/materials/Strang Calculus.ts'
import '@/data/materials/Stewart Calculus.ts'
import '@/data/materials/Princeton Calculus Reader.ts'
import '@/data/materials/史济怀 等 数分.ts'
import '@/data/materials/陈纪修 等 数分.ts'
import '@/data/materials/徐森林 等 数分.ts'
import '@/data/materials/何琛 史济怀 徐森林 数分.ts'
import '@/data/materials/陈纪修 等 数分习题.ts'
import '@/data/materials/徐森林 等 数分习题.ts'
import '@/data/materials/程艺 等 数分.ts'
import '@/data/materials/张筑生 数分.ts'
import '@/data/materials/H&N Applied Analysis.ts'
import '@/data/materials/S. Abbott, Understanding Analysis.ts'
import '@/data/materials/C. C. Pugh, Real Mathematical Analysis.ts'
import '@/data/materials/T. M. Apostol, Mathematical Analysis.ts'
import '@/data/materials/Rudin PMA.ts'
import '@/data/materials/Zorich, Mathematical Analysis.ts'
import "@/data/materials/Fikhtengol\'ts, Calculus.ts"
import '@/data/materials/R. Courant & F. John, Introduction to Calculus and Analysis.ts'
import '@/data/materials/刘思齐 数分选书.ts'
import '@/data/materials/分析学爱好者 我为何不建议初学者用清华丘班数分讲义学数分.ts'
import '@/data/materials/分析学爱好者 尽管数分教材千千万，但我却建议你学陈纪修.ts'
import '@/data/materials/分析学爱好者 对常见数分课本&习题集的快速版点评.ts'
import '@/data/materials/Jens Gustedt, Modern C.ts'
import '@/data/materials/cppreference.c.ts'
import '@/data/materials/Microsoft C++ Docs.ts'
import '@/data/materials/Bjarne Stroustrup, PPP C++.ts'
import '@/data/materials/Bjarne Stroustrup, A Tour of C++.ts'
import '@/data/materials/M. Gregoire, Professional C++.ts'
import '@/data/materials/cppreference.ts'
import '@/data/materials/The Definitive C++ Book Guide and List.ts'
import '@/data/materials/A. Stellman et al., Head First C♯.ts'
import '@/data/materials/Microsoft, A tour of the C♯ language.ts'
import '@/data/materials/屈婉玲 等 离散数学.ts'
import '@/data/materials/屈婉玲 等 离散数学教程.ts'
import '@/data/materials/K. H. Rosen, Discrete Mathematics and Its Applications.ts'
import '@/data/materials/M. Huth et al., Logic in Computer Science.ts'
import '@/data/materials/CMU, Logic and Proof.ts'
import '@/data/materials/J. A. Bondy et al., Graph Theory.ts'
import '@/data/materials/D. B. West, Introduction to Graph Theory.ts'
import '@/data/materials/J. M. Harris et al., Combinatorics and Graph Theory.ts'
import '@/data/materials/J. A. Beachy et al., Abstract Algebra.ts'
import '@/data/materials/Dummit & Foote, Abstract Algebra.ts'
import '@/data/materials/S. Lang, Undergraduate Algebra.ts'
import '@/data/materials/S. Lang, Algebra.ts'
import '@/data/materials/T. W. Judson, AATA.ts'
import '@/data/materials/席南华 基础代数.ts'
import '@/data/materials/Kostrikin, 代数学引论.ts'
import '@/data/materials/王树禾 图论.ts'
import '@/data/materials/丘维声 近世代数.ts'
import '@/data/materials/冯克勤 等 近世代数引论.ts'
import '@/data/materials/Oracle Learn Java.ts'
import '@/data/materials/K. Sierra et al., Head First Java.ts'
import '@/data/materials/Strang, Introduction to Linear Algebra.ts'
import '@/data/materials/GATech, Interactive Linear Algebra.ts'
import '@/data/materials/David C. Lay et al., Linear Algebra and Its Applications.ts'
import '@/data/materials/S. Axler, Linear Algebra Done Right.ts'
import '@/data/materials/S. R. Treil, Linear Algebra Done Wrong.ts'
import '@/data/materials/C. D. Meyer, Matrix Analysis and Applied Linear Algebra.ts'
import '@/data/materials/P. D. Lax, Linear Algebra and Its Applications.ts'
import '@/data/materials/R. A. Horn & C. R. Johnson, Matrix Analysis.ts'
import '@/data/materials/S. R. Garcia & R. A. Horn, Matrix Mathematics.ts'
import '@/data/materials/L. N. Trefethen & D. Bau, Numerical Linear Algebra.ts'
import '@/data/materials/T. S. Shores, Applied Linear Algebra and Matrix Analysis.ts'
import '@/data/materials/E. B. Saff & A. D. Snider, Matrix Fundamentals.ts'
import '@/data/materials/Jun Lu, Matrix Decomposition and Applications.ts'
import '@/data/materials/S. Lang, Linear Algebra.ts'
import '@/data/materials/M. Artin, Algebra.ts'
import '@/data/materials/S. J. Leon, Linear Algebra with Applications.ts'
import '@/data/materials/丘维声 高代.ts'
import '@/data/materials/丘维声 简明线性代数.ts'
import '@/data/materials/蓝以中 高代.ts'
import '@/data/materials/李炯生 等 线代.ts'
import '@/data/materials/李尚志 线代.ts'
import '@/data/materials/席南华 基础代数.ts'
import '@/data/materials/任广千 谢聪 胡翠芳 线性代数的几何意义.ts'
import '@/data/materials/陈发来 等 线代 非数.ts'
import '@/data/materials/陈发来 等 线代解几.ts'
import '@/data/materials/张贤科 许甫华 高代.ts'
import '@/data/materials/张贤科 高代.ts'
import '@/data/materials/谢启鸿 等 高代.ts'
import '@/data/materials/Kostrikin, 代数学引论.ts'
import '@/data/materials/分析学爱好者 我为什么推荐你使用丘维声学习高等代数.ts'
import '@/data/materials/PSF, The Python Tutorial.ts'
import '@/data/materials/E. Matthes, Python Crash Course.ts'
import '@/data/materials/嵩天 等 Python.ts'